"display_columns" = [
    "date_transacted",
    "posting_status",
    "key_code",
    "tier1_qualified",
    "short_description",
    "amount_sgd",
]

export_to_csv = false

[general]
strftime = "%d%b%y:%H%MH"
drop_na_threshold = 5

[general.directory]
outf01 = "output"


[column_headers]
"Transaction Date" = "date_transacted"
"Posting Date" = "date_posted"
"Description" = "description"
"Foreign Currency Type" = "currency_foreign"
"Transaction Amount(Foreign)" = "amount_foreign"
"Local Currency Type" = "currency"
"Transaction Amount(Local)" = "amount"


[category_to_int_keys]

"BUS/MRT" = 2
"SERAYA" = 0
"GRAB" = 0                       # Grab wallet top up are not qualified
"NUHMC-PHARMACY" = 0
"NUH" = 0                        # Medical bills are not qualified
"GIRO" = 0
"CR" = 0
"Previous" = 0
"AXS" = 0                        # AXS transactions are not qualified
"ATOME" = 0                      # ATOME is installment
"APPLE.COM/BILL" = 3
"CIRCLES.LIFE" = 4
"UOB ONE CASH REBATE" = 5
"ONE CARD ADDITIONAL REBATE" = 5
"PAYMT THRU E-BANK" = 0          # Credit card payments

[int_keys_to_qualification] ## True are qualified categories
"0" = false
"1" = true
"2" = false
"3" = true  # To track bills from Apple
"4" = true  # To track bills from Utilities
"5" = false # To track rebates


[viewer]
exclusions = ["GIRO PAYMENT"]
number_of_top_big_purchases = 20